spring:
  jpa:
    database-platform: org.allenarcher.discord.bot.persistence.SQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlite:sqlitesample.db
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always
    username: admin
    password: admin

commands:
  prefix: '!'
  unrecognized:
    text: Command '%s' is not recognized.
  help:
    text: This is some help text!
    aliases: help, h
  rank:
    aliases: rank, level, experience, xp